### ISSUE TITLE
[Eval error]

### ISSUE THREAD

**Issue by Ostyk** [dmorris0/PyramidCNN#2]
Hi,
I tried running your code after reading the awesome paper but I have run into an issue.

Which version of matconvnet-1 did you use? I got the latest from
[from here](https://www.vlfeat.org/matconvnet/download/). I'm asking because this path ```
`<MatConvNet>/matlab/mex` does not exist in the release or any previous one that I looked at. Would be greatful for some tips.
 
```
Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 91)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in runNetEdges (line 85)
        net.eval( {'input', img } );

Error in scoreEdgeNetOnData (line 45)
edgelist = runNetEdges( net, imglist, edgefolder, doGPU, redoEdges, crop, averageScales );

Error in runLeafNet (line 55)
scoreEdgeNetOnData( plantNames, segNames, outfolder, minfrac, edgeRadius, net, doGPU, redoEdges, redoSegs , [], doAverage  );

```

**Comment by dmorris0** [comment]
Sorry, it has been quite a while since I looked at the code.  vl_nnconv mex file should be somewhere in your path.

**Comment by Ostyk** [comment]
OK, I managed to re-build matconvnet and it works now. As per instructions given here [https://www.vlfeat.org/matconvnet/install/](https://www.vlfeat.org/matconvnet/install/). P.S. also needed to download the bioinformatics toolbox.
